package View;

import java.awt.*;

public class DisabledHome extends javax.swing.JPanel {

    /**
     * Creates new form ClientHome
     */
    public DisabledHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(Color.GRAY);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
}
